-- Behavior Trust Score: 0-100, default 50
CREATE TABLE IF NOT EXISTS user_trust (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    trust_score TINYINT UNSIGNED NOT NULL DEFAULT 50,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_trust_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
