-- SuperLike tables
CREATE TABLE IF NOT EXISTS user_superlike_balance (user_id BIGINT NOT NULL, balance INT NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (user_id)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS superlike_tx (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, type VARCHAR(20) NOT NULL, amount INT NOT NULL, video_id VARCHAR(24) NULL, livestream_id VARCHAR(24) NULL, meta JSON NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_superlike_tx_user (user_id), INDEX idx_superlike_tx_created (created_at)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS creator_monthly (id BIGINT AUTO_INCREMENT PRIMARY KEY, creator_id BIGINT NOT NULL, month VARCHAR(7) NOT NULL, received_total INT NOT NULL DEFAULT 0, eligible_total INT NOT NULL DEFAULT 0, payout_amount DECIMAL(12,2) NOT NULL DEFAULT 0, status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_creator_month (creator_id, month)) ENGINE=InnoDB;
